<?php
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/functions.php';
$mockup_whatsapp = whatsapp_number(get_setting('whatsapp', ''));
$mockup_whatsapp_message = rawurlencode(content_value('whatsapp_message', 'Hi Achievers Academy, I would like to know more.'));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mockup • Achievers Academy CMS</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="assets/css/style.css?v=20260909">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
</head>
<body class="bg-slate-100 py-12">
    <?php if ($mockup_whatsapp): ?><a class="whatsapp-float" href="https://wa.me/<?= e($mockup_whatsapp) ?>?text=<?= e($mockup_whatsapp_message) ?>" target="_blank" rel="noopener noreferrer" aria-label="<?= e(content_value('whatsapp_float_label', 'Chat on WhatsApp')) ?>"><i class="fa-brands fa-whatsapp" aria-hidden="true"></i><span>WhatsApp</span></a><?php endif; ?>
    <main class="max-w-7xl mx-auto px-6">
        <header class="text-center mb-10"><h1 class="text-5xl font-extrabold">Achievers Academy — Design Mockups</h1><p class="text-xl text-slate-600 mt-2">A preview of the public website and the CMS control panel.</p><div class="mt-4 flex flex-wrap justify-center gap-3"><a href="./" class="text-sm px-5 py-2 border rounded-full">← Live site</a><a href="admin/login.php" class="btn-primary">Open admin CMS</a></div></header>
        <section class="mb-16"><div class="flex items-center justify-between mb-4 px-1"><div><span class="text-xs font-bold px-3 py-1 bg-white rounded-full border">PUBLIC WEBSITE</span><span class="ml-2 font-semibold text-xl">Homepage mockup</span></div><span class="text-xs text-slate-500">Desktop + mobile</span></div>
            <div class="grid lg:grid-cols-12 gap-5"><div class="lg:col-span-8"><div class="device mx-auto max-w-[920px]"><div class="mockup-frame bg-white"><div class="bg-slate-800 px-4 py-2 flex items-center text-white text-xs"><div class="flex gap-1.5 mr-3"><i class="w-3 h-3 bg-red-500 rounded-full"></i><i class="w-3 h-3 bg-yellow-500 rounded-full"></i><i class="w-3 h-3 bg-green-500 rounded-full"></i></div><span class="bg-slate-700 px-3 py-0.5 rounded flex-1 text-center text-[10px]">https://achieversacademy.com</span></div><div class="mockup-hero"><img src="assets/images/hero-main.jpg" alt="Gymnastics training"><div><span class="inline px-4 py-1 bg-amber-400 text-slate-900 text-xs font-bold rounded-full">NAGPUR'S #1</span><h2>Train like a<br>champion</h2><p>Professional gymnastics pathways for confident athletes.</p><div class="mt-5 flex gap-2"><span class="bg-amber-400 text-slate-900 px-5 py-2 rounded-full text-sm font-bold">Explore programs</span><span class="border border-white/60 px-5 py-2 rounded-full text-sm">Achievements</span></div></div></div><div class="p-6"><div class="flex justify-between mb-4"><strong class="text-sm">Our training programs</strong><span class="text-xs text-amber-700">See all →</span></div><div class="grid grid-cols-3 gap-3"><div class="border rounded-xl overflow-hidden"><img src="assets/images/course-little.jpg" class="mockup-course-image" alt="Little Champions"><div class="p-3 text-xs font-semibold">Little Champions</div></div><div class="border rounded-xl overflow-hidden"><img src="assets/images/course-rising.jpg" class="mockup-course-image" alt="Rising Stars"><div class="p-3 text-xs font-semibold">Rising Stars</div></div><div class="border rounded-xl overflow-hidden"><img src="assets/images/course-national.jpg" class="mockup-course-image" alt="National Prep"><div class="p-3 text-xs font-semibold">National Prep</div></div></div></div></div></div></div></div>
                <div class="lg:col-span-4"><div class="device mx-auto w-[260px]"><div class="mockup-frame mockup-frame--mobile bg-white"><div class="mockup-mobile-hero"><img src="assets/images/hero-main.jpg" alt="Gymnastics training"><div><span>NAGPUR #1</span><h2>Train like a champion</h2><p>Safe, focused coaching</p><b>Explore programs</b></div></div><div class="p-3 text-xs bg-white"><strong>Our programs</strong><div class="space-y-1 text-[10px] mt-2"><div>Little Champions</div><div>Rising Stars</div></div></div></div></div></div>
            </div>
        </section>
        <section><div class="mb-4 px-1"><span class="text-xs font-bold px-3 py-1 bg-white rounded-full border">CMS ADMIN</span><span class="ml-2 font-semibold text-xl">Admin dashboard mockup</span></div><div class="bg-white border shadow-xl rounded-3xl overflow-hidden max-w-[1050px]"><div class="bg-slate-900 text-white px-6 py-3 flex items-center"><div class="flex items-center gap-2"><i class="w-7 h-7 bg-amber-400 text-slate-900 flex items-center justify-center text-sm font-extrabold rounded">A</i><span class="font-bold">Achievers CMS</span></div><span class="ml-auto text-xs px-3 py-1 bg-slate-800 rounded-full">admin</span></div><div class="flex"><aside class="w-52 bg-slate-800 text-slate-300 p-2 text-xs"><div class="px-3 py-2 text-amber-300 text-[10px] font-bold">ADMIN PANEL</div><div class="space-y-1"><div class="px-3 py-1.5 bg-slate-700 rounded text-white">📊 Dashboard</div><div class="px-3 py-1.5">🖼️ Banners</div><div class="px-3 py-1.5">✍️ Page Content</div><div class="px-3 py-1.5">🤸 Disciplines</div><div class="px-3 py-1.5">📩 Inquiries</div></div></aside><div class="flex-1 p-6"><div class="flex justify-between mb-4"><strong>Dashboard overview</strong><span class="text-xs text-emerald-600">Updated just now</span></div><div class="grid grid-cols-4 gap-3 mb-6"><div class="bg-slate-50 border p-3 rounded-2xl"><small>Total enquiries</small><strong class="block text-3xl">187</strong></div><div class="bg-slate-50 border p-3 rounded-2xl"><small>Active courses</small><strong class="block text-3xl">8</strong></div><div class="bg-slate-50 border p-3 rounded-2xl"><small>Gallery items</small><strong class="block text-3xl">42</strong></div><div class="bg-slate-50 border p-3 rounded-2xl"><small>Pending leads</small><strong class="block text-3xl text-amber-600">19</strong></div></div><strong class="text-sm">Recent leads</strong><table class="w-full text-xs mt-2"><tr class="border-b text-left text-slate-400"><th class="py-1.5">Name</th><th>Course</th><th>Status</th></tr><tr><td class="py-2">Aarav Sharma</td><td>Little Champions</td><td><span class="px-2 py-px bg-emerald-100 text-emerald-700 rounded">Enrolled</span></td></tr></table></div></div></div></section>
    </main>
</body>
</html>
